# Generated by Django 4.0.4 on 2022-05-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_alter_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=200)),
                ('image_file', models.FileField(upload_to='media/photos/')),
                ('dated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('dated',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='media/uploads/'),
        ),
    ]
