# Generated by Django 4.0.4 on 2022-05-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(to='photos.category'),
        ),
        migrations.AddField(
            model_name='image',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='photos.location'),
            preserve_default=False,
        ),
    ]
