# Generated by Django 4.0.4 on 2022-05-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_image_category_image_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ManyToManyField(related_name='images', to='photos.category'),
        ),
    ]
