# Generated by Django 4.0.4 on 2022-05-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_image_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='media/category/'),
        ),
    ]
