# Generated by Django 4.0.4 on 2022-05-29 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_remove_image_category_image_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url_link',
        ),
    ]
