# Generated by Django 4.0.4 on 2022-05-29 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_remove_image_url_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-dated',)},
        ),
    ]
